export const ACTION_SIGNIN = 'ACTION_SIGNIN';
export const ACTION_SIGNIN_SUCCESS = 'ACTION_SIGNIN_SUCCESS';
export const ACTION_SIGNIN_FAILED = 'ACTION_SIGNIN_FAILED';

export const ACTION_REGISTER = 'ACTION_REGISTER';
export const ACTION_REGISTER_SUCCESS = 'ACTION_REGISTER_SUCCESS';
export const ACTION_REGISTER_FAILED = 'ACTION_REGISTER_FAILED';

export const ACTION_LOGOUT = 'ACTION_LOGOUT';

export const ACTION_SESSION_CHECKING = 'ACTION_SESSION_CHECKING';
export const ACTION_SESSION_CHECKING_SUCCESS = 'ACTION_SESSION_CHECKING_SUCCESS';
export const ACTION_SESSION_CHECKING_FAILED = 'ACTION_SESSION_CHECKING_FAILED';

export const ACTION_POST_REQUEST_STORY = 'ACTION_POST_REQUEST_STORY';
export const ACTION_POST_REQUEST_STORY_SUCCESS = 'ACTION_POST_REQUEST_STORY_SUCCESS';
export const ACTION_POST_REQUEST_STORY_FAILED = 'ACTION_POST_REQUEST_STORY_FAILED';

